spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: ${STUDENTS_URL}
          predicates:
            - Path=/api/v1/students/**
        - id: schools
          uri: http://localhost:${SCHOOLS_PORT}
          predicates:
            - Path=/api/v1/schools/**

management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true
    zipkin:
      tracing:
        endpoint: ${ZIPKIN_ENDPOINT}
    endpoints:
      web:
        exposure:
          include: health,metrics,prometheus
