eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME}
  client:
    service-url:
      defaultZone: http://localhost:${EUREKA_PORT}/eureka

server:
  port: ${STUDENTS_PORT}
spring:
  application:
    name: students
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}/students
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    initialize: true
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
